language: java

jdk:
  - openjdk8

branches:
  only:
    - develop

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.mvnw'

script: 'mvn -f reminder-be/pom.xml clean package'

notifications:
  email:
    recipients:
      - deveely@kakao.com
