spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dlgusrb0808@gmail.com
    password: cjsrn1992!
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true